### ISSUE TITLE
How to early return from pipeline definition?

### ISSUE THREAD

**Issue by zzak** [Gusto/buildkite-builder#111]
I have a pipeline similar to:

```ruby
Buildkite::Builder.pipeline do
  if build_skipped?
    command do
      label "skip"
      command "echo 'Build skipped'"
    end
    
    # break
  end
  
  # rest of pipeline
end
```

But due to this code, there isn't a clean way to exit early:
https://github.com/Gusto/buildkite-builder/blob/deedcfb4d036b5a51d25ba813a9acc6bc917dd1a/lib/buildkite/builder/pipeline.rb#L75

I'm not sure if throw/catch would be a good solution here, but otherwise the workaround is to wrap the whole rest of the pipeline in an `else` which should be avoidable.

**Comment by ngan** [comment]
So funny that I encountered a need for this very recently! I haven't had a chance to try it out yet, but does `next` work for you?

```
Buildkite::Builder.pipeline do
  if build_skipped?
    command do
      label "skip"
      command "echo 'Build skipped'"
    end
    
    next
  end
  
  # rest of pipeline
end
```

**Comment by zzak** [comment]
I tried everything but `next` :joy: that worked!

Thank you!! :bow:
