### ISSUE TITLE
Github repo regex should support resolving without .git suffix

### ISSUE THREAD

**Issue by drwl** [Gusto/buildkite-builder#32]
`REPO_REGEX = /github\.com(?::|\/)(.*)\.git\z/.freeze`

This regex should be made to support `https://github.com/Gusto/buildkite-builder` and `https://github.com/Gusto/buildkite-builder.git`.

Potential fix: `REPO = ENV['BUILDKITE_REPO'][/github\.com:(.+)/, 1].freeze`

**Comment by technicalpickles** [comment]
Looks like this was fixed in https://github.com/Gusto/buildkite-builder/pull/33
