### ISSUE TITLE
error running on Ruby 2.6

### ISSUE THREAD

**Issue by rjnienaber-gusto** [Gusto/buildkite-builder#69]
Looks like there's a bug when running on Ruby 2.6:

```
/gems/buildkite-builder-3.4.0/lib/buildkite/builder/data.rb:21:in `method_missing': undefined method `end_with?' for :env=:Symbol (NoMethodError)
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/extensions/env.rb:6:in `prepare'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/extension.rb:22:in `initialize'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/extension_manager.rb:19:in `new'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/extension_manager.rb:19:in `use'
  from /Users/richard.nienaber/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/forwardable.rb:230:in `use'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/pipeline.rb:37:in `initialize'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/commands/run.rb:23:in `new'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/commands/run.rb:23:in `run'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/commands/abstract.rb:54:in `execute'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/commands/abstract.rb:25:in `execute'
  from /gems/buildkite-builder-3.4.0/lib/buildkite/builder/commands.rb:27:in `run'
  from /gems/buildkite-builder-3.4.0/exe/buildkite-builder:6:in `<top (required)>'
  from /bin/buildkite-builder:23:in `load'
  from /bin/buildkite-builder:23:in `<main>
```

This makes sense because the `.end_with?` method was only [added to symbols in Ruby 2.7](https://rubyreferences.github.io/rubychanges/2.7.html#symbolstart_with-and-end_with). Not sure if the code should be fixed or the required ruby version should be upped to 2.7 considering that [2.6 is end-of-life as of 31 Mar 2022](https://endoflife.date/ruby).

**Comment by rjnienaber-gusto** [comment]
I was able to workaround this by monkeypatching `Symbol` and invoking `Buildkite-Builder` as a library:

```
class Symbol
  def end_with?(*args, &block)
    to_s.end_with?(*args, &block)
  end
end

require 'buildkite-builder'

Buildkite::Builder::Commands.run
```

**Comment by technicalpickles** [comment]
We've been running buildkite-builder internally on Ruby 3.x for awhile now. You can see the docker image running it here:

https://github.com/Gusto/buildkite-builder/blob/1c2be083bf8fa92b8d5d57637bb73fb0cbb73d8f/Dockerfile#L1

I don't think it makes sense to add 2.6 support, and we don't even have 2.7 support currently from what I recall (don't have an error handy). That is coming up on its own EOL next March. I'm not sure it makes sense to update for 2.7 even.

@tubaxenor @ngan what do y'all think?

I can update the required version to reflect reality in the mean time.
